name: Pull Request Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out base branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - name: Check out head branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: head

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Run validation script
        run: php .github/workflows/validate_pr.php
